#!/usr/bin/env bash
cd "$(dirname "$0")/.."
[ $PORT ]     || PORT=5000
[ $RACK_ENV ] || RACK_ENV=development

cmd="bundle exec rackup -I lib -s thin -p $PORT"
[[ $RACK_ENV == "development" ]] && exec rerun "$cmd -o 127.0.0.1"
exec $cmd

